import { compile } from '@mdx-js/mdx'
import remarkGfm from 'remark-gfm'
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, basename, join, relative } from 'node:path'
import matter from 'gray-matter'
import sharp from 'sharp'

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const CONTENT_DIR = join(ROOT, 'content/blog')
const GENERATED_DIR = join(ROOT, 'src/generated/blog')
const GENERATED_INDEX = join(ROOT, 'src/generated/blog-index.ts')
const GENERATED_META = join(ROOT, 'src/generated/blog-meta.json')
const GENERATED_PATHS = join(ROOT, 'src/generated/blog-prerender-paths.json')
const PUBLIC_BLOG_DIR = join(ROOT, 'public/blog')

const HERO_WIDTH = 1200
const VALID_TOOL_IDS = new Set([
  'squoosh-alternative',
  'heic-to-jpg',
  'batch-image-compressor',
  'avif-compressor',
])

const VALID_CLUSTER_IDS = new Set([
  'image-compression',
  'format-conversion',
  'performance-seo',
])

const BLOG_CLUSTER_PATHS = [
  '/blog/image-compression',
  '/blog/format-conversion',
  '/blog/performance-seo',
]

function canonicalBlogPath(slug, cluster) {
  return cluster ? `/blog/${cluster}/${slug}` : `/blog/${slug}`
}

function slugify(value) {
  return String(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

function slugToImportName(slug) {
  const parts = slug.split('-').filter(Boolean)
  return `Post${parts.map((part) => part[0].toUpperCase() + part.slice(1)).join('')}`
}

function estimateReadingTime(text) {
  const words = text.trim().split(/\s+/).filter(Boolean).length
  return Math.max(1, Math.round(words / 220))
}

function excerptFromBody(body, maxLength = 160) {
  const plain = body
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/[#>*_\[\]()!`]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()

  if (plain.length <= maxLength) return plain
  return `${plain.slice(0, maxLength - 1).trim()}…`
}

async function compileMdxModule(slug, body) {
  const compiled = String(
    await compile(body, {
      development: false,
      outputFormat: 'program',
      providerImportSource: '@/components/blog/mdx-components',
      remarkPlugins: [remarkGfm],
    }),
  )

  return `// @ts-nocheck
// Generated by scripts/compile-blog.mjs — do not edit.
${compiled}
`
}

async function processHeroImage(slug, heroImageBase) {
  const assetDir = join(CONTENT_DIR, 'assets', slug)
  const candidates = ['png', 'jpg', 'jpeg', 'webp'].map((ext) =>
    join(assetDir, `${heroImageBase}.${ext}`),
  )
  const sourcePath = candidates.find((path) => existsSync(path))

  if (!sourcePath) {
    console.warn(`  ⚠ No hero source for ${slug} (expected assets/${slug}/${heroImageBase}.*)`)
    return null
  }

  const outDir = join(PUBLIC_BLOG_DIR, slug)
  mkdirSync(outDir, { recursive: true })

  const pipeline = sharp(sourcePath).resize({
    width: HERO_WIDTH,
    withoutEnlargement: true,
  })

  await pipeline.clone().avif({ quality: 62, effort: 4 }).toFile(join(outDir, `${heroImageBase}.avif`))
  await pipeline.clone().webp({ quality: 82 }).toFile(join(outDir, `${heroImageBase}.webp`))
  await pipeline
    .clone()
    .jpeg({ quality: 85, mozjpeg: true })
    .toFile(join(outDir, `${heroImageBase}.jpg`))

  console.log(`  ✓ ${slug}/${heroImageBase}.avif + .webp + .jpg`)

  return {
    avif: `/blog/${slug}/${heroImageBase}.avif`,
    webp: `/blog/${slug}/${heroImageBase}.webp`,
    jpeg: `/blog/${slug}/${heroImageBase}.jpg`,
  }
}

function validateFrontmatter(data, fileName) {
  const slug = slugify(data.slug ?? basename(fileName, '.mdx'))
  const title = String(data.title ?? '').trim()
  const description = String(data.description ?? '').trim()
  const publishedAt = String(data.publishedAt ?? '').trim()

  if (!title) throw new Error(`${fileName}: missing title`)
  if (!description) throw new Error(`${fileName}: missing description`)
  if (!publishedAt) throw new Error(`${fileName}: missing publishedAt`)

  const relatedTools = Array.isArray(data.relatedTools)
    ? data.relatedTools.filter((id) => VALID_TOOL_IDS.has(id))
    : []

  const faq = Array.isArray(data.faq)
    ? data.faq
        .map((item) => ({
          question: String(item?.question ?? '').trim(),
          answer: String(item?.answer ?? '').trim(),
        }))
        .filter((item) => item.question && item.answer)
    : []

  const keywords = Array.isArray(data.keywords)
    ? data.keywords.map(String).join(', ')
    : String(data.keywords ?? '').trim()

  return {
    slug,
    title,
    description,
    publishedAt,
    updatedAt: data.updatedAt ? String(data.updatedAt).trim() : undefined,
    keywords,
    cluster: VALID_CLUSTER_IDS.has(data.cluster) ? data.cluster : null,
    heroImage: String(data.heroImage ?? 'hero').trim(),
    heroImageAlt: String(data.heroImageAlt ?? title).trim(),
    readingTimeMinutes:
      typeof data.readingTimeMinutes === 'number'
        ? data.readingTimeMinutes
        : undefined,
    relatedTools,
    faq,
  }
}

function ensureEmptyBlogOutputs() {
  mkdirSync(join(ROOT, 'src/generated'), { recursive: true })
  rmSync(GENERATED_DIR, { recursive: true, force: true })
  mkdirSync(GENERATED_DIR, { recursive: true })

  writeFileSync(
    GENERATED_INDEX,
    `// Generated by scripts/compile-blog.mjs — do not edit.
import type { BlogPostMeta } from '@/lib/blog/types'
import type { ComponentType } from 'react'

export const BLOG_POSTS: BlogPostMeta[] = []

export const BLOG_POST_SLUGS: string[] = []

const BLOG_POST_CONTENT: Record<string, ComponentType> = {}

export function getBlogPostContent(slug: string): ComponentType | undefined {
  return BLOG_POST_CONTENT[slug]
}

export function getBlogPost(slug: string): BlogPostMeta | undefined {
  return BLOG_POSTS.find((post) => post.slug === slug)
}

export function getLatestBlogPosts(limit = 3): BlogPostMeta[] {
  return BLOG_POSTS.slice(0, limit)
}
`,
  )

  writeFileSync(GENERATED_META, `${JSON.stringify({ posts: [] }, null, 2)}\n`)
  writeFileSync(GENERATED_PATHS, '[]\n')
}

async function main() {
  if (!existsSync(CONTENT_DIR)) {
    ensureEmptyBlogOutputs()
    console.log('No content/blog directory — wrote empty blog index.')
    return
  }

  const mdxFiles = readdirSync(CONTENT_DIR)
    .filter((file) => file.endsWith('.mdx'))
    .sort()

  if (mdxFiles.length === 0) {
    ensureEmptyBlogOutputs()
    console.log('No MDX posts found — wrote empty blog index.')
    return
  }

  rmSync(GENERATED_DIR, { recursive: true, force: true })
  mkdirSync(GENERATED_DIR, { recursive: true })
  mkdirSync(PUBLIC_BLOG_DIR, { recursive: true })

  const posts = []

  for (const fileName of mdxFiles) {
    const sourcePath = join(CONTENT_DIR, fileName)
    const raw = readFileSync(sourcePath, 'utf8')
    const { content: body, data } = matter(raw)
    const meta = validateFrontmatter(data, fileName)

    const readingTimeMinutes =
      meta.readingTimeMinutes ?? estimateReadingTime(body)
    const excerpt = excerptFromBody(body)
    const heroPaths = await processHeroImage(meta.slug, meta.heroImage)

    const modulePath = join(GENERATED_DIR, `${meta.slug}.tsx`)
    writeFileSync(modulePath, await compileMdxModule(meta.slug, body))

    posts.push({
      ...meta,
      path: canonicalBlogPath(meta.slug, meta.cluster),
      legacyPath: `/blog/${meta.slug}`,
      excerpt,
      readingTimeMinutes,
      heroAvif: heroPaths?.avif ?? null,
      heroWebp: heroPaths?.webp ?? null,
      heroJpeg: heroPaths?.jpeg ?? null,
      sourceFile: relative(ROOT, sourcePath),
    })

    console.log(`  ✓ ${meta.slug}`)
  }

  posts.sort((a, b) => Date.parse(b.publishedAt) - Date.parse(a.publishedAt))

  const importLines = posts.map(
    (post) => `import ${slugToImportName(post.slug)} from './blog/${post.slug}'`,
  )
  const contentMapLines = posts.map(
    (post) => `  '${post.slug}': ${slugToImportName(post.slug)},`,
  )

  writeFileSync(
    GENERATED_INDEX,
    `// Generated by scripts/compile-blog.mjs — do not edit.
import type { BlogPostMeta } from '@/lib/blog/types'
import type { ComponentType } from 'react'
${importLines.join('\n')}

export const BLOG_POSTS: BlogPostMeta[] = ${JSON.stringify(posts, null, 2)}

export const BLOG_POST_SLUGS: string[] = ${JSON.stringify(posts.map((p) => p.slug))}

const BLOG_POST_CONTENT: Record<string, ComponentType> = {
${contentMapLines.join('\n')}
}

export function getBlogPostContent(slug: string): ComponentType | undefined {
  return BLOG_POST_CONTENT[slug]
}

export function getBlogPost(slug: string): BlogPostMeta | undefined {
  return BLOG_POSTS.find((post) => post.slug === slug)
}

export function getLatestBlogPosts(limit = 3): BlogPostMeta[] {
  return BLOG_POSTS.slice(0, limit)
}
`,
  )

  writeFileSync(
    GENERATED_META,
    `${JSON.stringify(
      {
        posts: posts.map((post) => ({
          slug: post.slug,
          path: post.path,
          title: post.title,
          description: post.description,
          publishedAt: post.publishedAt,
          updatedAt: post.updatedAt,
          cluster: post.cluster,
          sourceFile: post.sourceFile,
        })),
      },
      null,
      2,
    )}\n`,
  )

  writeFileSync(
    GENERATED_PATHS,
    `${JSON.stringify([...BLOG_CLUSTER_PATHS, ...posts.map((post) => post.path)])}\n`,
  )

  console.log(`Compiled ${posts.length} blog posts → src/generated/blog/`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
