import { mkdirSync, writeFileSync } from 'node:fs'
import { resolveAppVersion } from './lib/app-version.mjs'

const version = resolveAppVersion()
const payload = { version, builtAt: new Date().toISOString() }

writeFileSync('public/version.json', `${JSON.stringify(payload)}\n`)

mkdirSync('src/generated', { recursive: true })
writeFileSync(
  'src/generated/app-version.ts',
  `// Generated by scripts/generate-version.mjs — do not edit.\nexport const APP_VERSION = ${JSON.stringify(version)}\n`,
)

console.log(`Wrote public/version.json and src/generated/app-version.ts → ${version}`)
