import { mkdirSync, writeFileSync } from 'node:fs'
import { resolveAppVersion } from './lib/app-version.mjs'

const version = resolveAppVersion()
const payload = { version, builtAt: new Date().toISOString() }

writeFileSync('public/version.json', `${JSON.stringify(payload)}\n`)

mkdirSync('src/generated', { recursive: true })
writeFileSync(
  'src/generated/app-version.ts',
  `// Generated by scripts/generate-version.mjs — do not edit.\nexport const APP_VERSION = ${JSON.stringify(version)}\n`,
)

const sentryReleaseSource = `// Generated by scripts/generate-version.mjs — do not edit.
export const SENTRY_RELEASE: string = ${JSON.stringify(version)}
`

writeFileSync('src/generated/sentry-release.ts', sentryReleaseSource)
writeFileSync(
  'sentry-release.mjs',
  `// Generated by scripts/generate-version.mjs — do not edit.
export const SENTRY_RELEASE = ${JSON.stringify(version)}

export function getSentryRelease() {
  return SENTRY_RELEASE === 'dev' ? undefined : SENTRY_RELEASE
}
`,
)

console.log(
  `Wrote public/version.json, src/generated/app-version.ts, src/generated/sentry-release.ts, sentry-release.mjs → ${version}`,
)
