/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SquooshAlternativeRouteImport } from './routes/squoosh-alternative'
import { Route as PrivacyFirstImageCompressionRouteImport } from './routes/privacy-first-image-compression'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthorRouteImport } from './routes/author'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ToolsBatchImageCompressorRouteImport } from './routes/tools/batch-image-compressor'
import { Route as StudioConversionRouteImport } from './routes/studio/$conversion'
import { Route as ConvertHeicToJpgRouteImport } from './routes/convert/heic-to-jpg'
import { Route as CompressUnder50kbRouteImport } from './routes/compress/under-50kb'
import { Route as CompressUnder200kbRouteImport } from './routes/compress/under-200kb'
import { Route as CompressUnder100kbRouteImport } from './routes/compress/under-100kb'
import { Route as CompressAvifRouteImport } from './routes/compress/avif'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiSentryExampleRouteImport } from './routes/api/sentry-example'
import { Route as BlogClusterIdSlugRouteImport } from './routes/blog/$clusterId/$slug'

const SquooshAlternativeRoute = SquooshAlternativeRouteImport.update({
  id: '/squoosh-alternative',
  path: '/squoosh-alternative',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyFirstImageCompressionRoute =
  PrivacyFirstImageCompressionRouteImport.update({
    id: '/privacy-first-image-compression',
    path: '/privacy-first-image-compression',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRoute = AuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBatchImageCompressorRoute =
  ToolsBatchImageCompressorRouteImport.update({
    id: '/tools/batch-image-compressor',
    path: '/tools/batch-image-compressor',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudioConversionRoute = StudioConversionRouteImport.update({
  id: '/studio/$conversion',
  path: '/studio/$conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertHeicToJpgRoute = ConvertHeicToJpgRouteImport.update({
  id: '/convert/heic-to-jpg',
  path: '/convert/heic-to-jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressUnder50kbRoute = CompressUnder50kbRouteImport.update({
  id: '/compress/under-50kb',
  path: '/compress/under-50kb',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressUnder200kbRoute = CompressUnder200kbRouteImport.update({
  id: '/compress/under-200kb',
  path: '/compress/under-200kb',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressUnder100kbRoute = CompressUnder100kbRouteImport.update({
  id: '/compress/under-100kb',
  path: '/compress/under-100kb',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressAvifRoute = CompressAvifRouteImport.update({
  id: '/compress/avif',
  path: '/compress/avif',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSentryExampleRoute = ApiSentryExampleRouteImport.update({
  id: '/api/sentry-example',
  path: '/api/sentry-example',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogClusterIdSlugRoute = BlogClusterIdSlugRouteImport.update({
  id: '/blog/$clusterId/$slug',
  path: '/blog/$clusterId/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/author': typeof AuthorRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-first-image-compression': typeof PrivacyFirstImageCompressionRoute
  '/squoosh-alternative': typeof SquooshAlternativeRoute
  '/api/sentry-example': typeof ApiSentryExampleRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compress/avif': typeof CompressAvifRoute
  '/compress/under-100kb': typeof CompressUnder100kbRoute
  '/compress/under-200kb': typeof CompressUnder200kbRoute
  '/compress/under-50kb': typeof CompressUnder50kbRoute
  '/convert/heic-to-jpg': typeof ConvertHeicToJpgRoute
  '/studio/$conversion': typeof StudioConversionRoute
  '/tools/batch-image-compressor': typeof ToolsBatchImageCompressorRoute
  '/blog/': typeof BlogIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/blog/$clusterId/$slug': typeof BlogClusterIdSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/author': typeof AuthorRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-first-image-compression': typeof PrivacyFirstImageCompressionRoute
  '/squoosh-alternative': typeof SquooshAlternativeRoute
  '/api/sentry-example': typeof ApiSentryExampleRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compress/avif': typeof CompressAvifRoute
  '/compress/under-100kb': typeof CompressUnder100kbRoute
  '/compress/under-200kb': typeof CompressUnder200kbRoute
  '/compress/under-50kb': typeof CompressUnder50kbRoute
  '/convert/heic-to-jpg': typeof ConvertHeicToJpgRoute
  '/studio/$conversion': typeof StudioConversionRoute
  '/tools/batch-image-compressor': typeof ToolsBatchImageCompressorRoute
  '/blog': typeof BlogIndexRoute
  '/studio': typeof StudioIndexRoute
  '/blog/$clusterId/$slug': typeof BlogClusterIdSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/author': typeof AuthorRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-first-image-compression': typeof PrivacyFirstImageCompressionRoute
  '/squoosh-alternative': typeof SquooshAlternativeRoute
  '/api/sentry-example': typeof ApiSentryExampleRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compress/avif': typeof CompressAvifRoute
  '/compress/under-100kb': typeof CompressUnder100kbRoute
  '/compress/under-200kb': typeof CompressUnder200kbRoute
  '/compress/under-50kb': typeof CompressUnder50kbRoute
  '/convert/heic-to-jpg': typeof ConvertHeicToJpgRoute
  '/studio/$conversion': typeof StudioConversionRoute
  '/tools/batch-image-compressor': typeof ToolsBatchImageCompressorRoute
  '/blog/': typeof BlogIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/blog/$clusterId/$slug': typeof BlogClusterIdSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/author'
    | '/privacy'
    | '/privacy-first-image-compression'
    | '/squoosh-alternative'
    | '/api/sentry-example'
    | '/blog/$slug'
    | '/compress/avif'
    | '/compress/under-100kb'
    | '/compress/under-200kb'
    | '/compress/under-50kb'
    | '/convert/heic-to-jpg'
    | '/studio/$conversion'
    | '/tools/batch-image-compressor'
    | '/blog/'
    | '/studio/'
    | '/blog/$clusterId/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/author'
    | '/privacy'
    | '/privacy-first-image-compression'
    | '/squoosh-alternative'
    | '/api/sentry-example'
    | '/blog/$slug'
    | '/compress/avif'
    | '/compress/under-100kb'
    | '/compress/under-200kb'
    | '/compress/under-50kb'
    | '/convert/heic-to-jpg'
    | '/studio/$conversion'
    | '/tools/batch-image-compressor'
    | '/blog'
    | '/studio'
    | '/blog/$clusterId/$slug'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/author'
    | '/privacy'
    | '/privacy-first-image-compression'
    | '/squoosh-alternative'
    | '/api/sentry-example'
    | '/blog/$slug'
    | '/compress/avif'
    | '/compress/under-100kb'
    | '/compress/under-200kb'
    | '/compress/under-50kb'
    | '/convert/heic-to-jpg'
    | '/studio/$conversion'
    | '/tools/batch-image-compressor'
    | '/blog/'
    | '/studio/'
    | '/blog/$clusterId/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AuthorRoute: typeof AuthorRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyFirstImageCompressionRoute: typeof PrivacyFirstImageCompressionRoute
  SquooshAlternativeRoute: typeof SquooshAlternativeRoute
  ApiSentryExampleRoute: typeof ApiSentryExampleRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CompressAvifRoute: typeof CompressAvifRoute
  CompressUnder100kbRoute: typeof CompressUnder100kbRoute
  CompressUnder200kbRoute: typeof CompressUnder200kbRoute
  CompressUnder50kbRoute: typeof CompressUnder50kbRoute
  ConvertHeicToJpgRoute: typeof ConvertHeicToJpgRoute
  StudioConversionRoute: typeof StudioConversionRoute
  ToolsBatchImageCompressorRoute: typeof ToolsBatchImageCompressorRoute
  BlogIndexRoute: typeof BlogIndexRoute
  StudioIndexRoute: typeof StudioIndexRoute
  BlogClusterIdSlugRoute: typeof BlogClusterIdSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/squoosh-alternative': {
      id: '/squoosh-alternative'
      path: '/squoosh-alternative'
      fullPath: '/squoosh-alternative'
      preLoaderRoute: typeof SquooshAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-first-image-compression': {
      id: '/privacy-first-image-compression'
      path: '/privacy-first-image-compression'
      fullPath: '/privacy-first-image-compression'
      preLoaderRoute: typeof PrivacyFirstImageCompressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/batch-image-compressor': {
      id: '/tools/batch-image-compressor'
      path: '/tools/batch-image-compressor'
      fullPath: '/tools/batch-image-compressor'
      preLoaderRoute: typeof ToolsBatchImageCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$conversion': {
      id: '/studio/$conversion'
      path: '/studio/$conversion'
      fullPath: '/studio/$conversion'
      preLoaderRoute: typeof StudioConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert/heic-to-jpg': {
      id: '/convert/heic-to-jpg'
      path: '/convert/heic-to-jpg'
      fullPath: '/convert/heic-to-jpg'
      preLoaderRoute: typeof ConvertHeicToJpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress/under-50kb': {
      id: '/compress/under-50kb'
      path: '/compress/under-50kb'
      fullPath: '/compress/under-50kb'
      preLoaderRoute: typeof CompressUnder50kbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress/under-200kb': {
      id: '/compress/under-200kb'
      path: '/compress/under-200kb'
      fullPath: '/compress/under-200kb'
      preLoaderRoute: typeof CompressUnder200kbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress/under-100kb': {
      id: '/compress/under-100kb'
      path: '/compress/under-100kb'
      fullPath: '/compress/under-100kb'
      preLoaderRoute: typeof CompressUnder100kbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress/avif': {
      id: '/compress/avif'
      path: '/compress/avif'
      fullPath: '/compress/avif'
      preLoaderRoute: typeof CompressAvifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sentry-example': {
      id: '/api/sentry-example'
      path: '/api/sentry-example'
      fullPath: '/api/sentry-example'
      preLoaderRoute: typeof ApiSentryExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$clusterId/$slug': {
      id: '/blog/$clusterId/$slug'
      path: '/blog/$clusterId/$slug'
      fullPath: '/blog/$clusterId/$slug'
      preLoaderRoute: typeof BlogClusterIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AuthorRoute: AuthorRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyFirstImageCompressionRoute: PrivacyFirstImageCompressionRoute,
  SquooshAlternativeRoute: SquooshAlternativeRoute,
  ApiSentryExampleRoute: ApiSentryExampleRoute,
  BlogSlugRoute: BlogSlugRoute,
  CompressAvifRoute: CompressAvifRoute,
  CompressUnder100kbRoute: CompressUnder100kbRoute,
  CompressUnder200kbRoute: CompressUnder200kbRoute,
  CompressUnder50kbRoute: CompressUnder50kbRoute,
  ConvertHeicToJpgRoute: ConvertHeicToJpgRoute,
  StudioConversionRoute: StudioConversionRoute,
  ToolsBatchImageCompressorRoute: ToolsBatchImageCompressorRoute,
  BlogIndexRoute: BlogIndexRoute,
  StudioIndexRoute: StudioIndexRoute,
  BlogClusterIdSlugRoute: BlogClusterIdSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
